spring:
  datasource:
    url: jdbc:postgresql://db.mnsgsfjlejvlbdvjmcjo.supabase.co:5432/postgres
    username: postgres
    password: "KU7xLfPQ2LOb3NAI"
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true